DROP TABLE IF EXISTS `roms`;
CREATE TABLE `roms` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `device` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '设备代号，如 taiko、leedsa',
  `code` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '设备代码，如 taiko_global',
  `type` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '系统类型：MIUI / HyperOS',
  `bigver` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '大版本号，如 HyperOS 3、MIUI 14',
  `region` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '区域代号：cn/global/in/eea 等',
  `tag` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'ROM 标签，如 CnOO、MIXM',
  `branch` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '分支类型：F=正式版、X=开发版',
  `zone` int DEFAULT NULL COMMENT '区域分区：1=中国、2=国际',
  `version` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '完整版本号，如 OS3.0.303.0.WOVCNXM',
  `android` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Android 版本号，如 16.0、14.0',
  `beta_date` date DEFAULT NULL COMMENT 'Beta/内测发布日期',
  `release_date` date DEFAULT NULL COMMENT '正式发布日期',
  `public_date` date DEFAULT NULL COMMENT '公开发布日期',
  `recovery` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Recovery 包文件名',
  `fastboot` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Fastboot 包文件名',
  `ctelecom` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '中国电信定制包文件名',
  `cmobile` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '中国移动定制包文件名',
  `cunicom` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '中国联通定制包文件名',
  `others` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '其他渠道包文件名',
  `insdate` date DEFAULT NULL COMMENT '记录录入日期',
  `update_date` bigint DEFAULT NULL COMMENT '记录更新时间戳',
  `logs_zh` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '中文更新日志，logs 表 ID 引用结构（见 logs.sql）',
  `logs_en` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '英文更新日志，logs 表 ID 引用结构（见 logs.sql）',
  `logs_zh_tw` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '繁体中文（zh-Hant）更新日志，logs 表 ID 引用结构（见 logs.sql）',
  `logs_ug` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '维吾尔文（ug_CN）更新日志，logs 表 ID 引用结构（见 logs.sql）',
  `logs_bo` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '藏文（bo_CN）更新日志，logs 表 ID 引用结构（见 logs.sql）',
  `logs_ja` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '日文（ja）更新日志，logs 表 ID 引用结构（见 logs.sql）',
  `logs_ko` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '韩文（ko）更新日志，logs 表 ID 引用结构（见 logs.sql）',
  `logs_ru` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '俄文（ru）更新日志，logs 表 ID 引用结构（见 logs.sql）',
  `logs_uk` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '乌克兰文（uk）更新日志，logs 表 ID 引用结构（见 logs.sql）',
  `logs_pl` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '波兰文（pl）更新日志，logs 表 ID 引用结构（见 logs.sql）',
  `logs_de` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '德文（de）更新日志，logs 表 ID 引用结构（见 logs.sql）',
  `logs_fr` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '法文（fr）更新日志，logs 表 ID 引用结构（见 logs.sql）',
  `logs_it` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '意大利文（it）更新日志，logs 表 ID 引用结构（见 logs.sql）',
  `logs_es` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '西班牙文（es）更新日志，logs 表 ID 引用结构（见 logs.sql）',
  `logs_pt` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '葡萄牙文（pt）更新日志，logs 表 ID 引用结构（见 logs.sql）',
  `logs_tr` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '土耳其文（tr）更新日志，logs 表 ID 引用结构（见 logs.sql）',
  `logs_in` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '印地语（hi）更新日志，logs 表 ID 引用结构（见 logs.sql）',
  `logs_id` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '印尼文（id）更新日志，logs 表 ID 引用结构（见 logs.sql）',
  `logs_vi` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '越南文（vi）更新日志，logs 表 ID 引用结构（见 logs.sql）',
  `logs_th` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '泰文（th）更新日志，logs 表 ID 引用结构（见 logs.sql）',
  `logs_ar` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '阿拉伯文（ar）更新日志，logs 表 ID 引用结构（见 logs.sql）',
  `aspatch` date DEFAULT NULL COMMENT '安卓安全补丁日期',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_roms_device` (`device`),
  KEY `idx_roms_code` (`code`),
  KEY `idx_roms_device_type` (`device`,`type`),
  KEY `idx_roms_beta_date` (`beta_date`),
  KEY `idx_roms_release_date` (`release_date`),
  CONSTRAINT `roms_chk_1` CHECK (json_valid(`logs_zh`)),
  CONSTRAINT `roms_chk_2` CHECK (json_valid(`logs_en`)),
  CONSTRAINT `roms_chk_3` CHECK (json_valid(`logs_zh_tw`)),
  CONSTRAINT `roms_chk_4` CHECK (json_valid(`logs_ja`)),
  CONSTRAINT `roms_chk_5` CHECK (json_valid(`logs_ko`)),
  CONSTRAINT `roms_chk_6` CHECK (json_valid(`logs_ru`)),
  CONSTRAINT `roms_chk_7` CHECK (json_valid(`logs_uk`)),
  CONSTRAINT `roms_chk_8` CHECK (json_valid(`logs_pl`)),
  CONSTRAINT `roms_chk_9` CHECK (json_valid(`logs_de`)),
  CONSTRAINT `roms_chk_10` CHECK (json_valid(`logs_fr`)),
  CONSTRAINT `roms_chk_11` CHECK (json_valid(`logs_it`)),
  CONSTRAINT `roms_chk_12` CHECK (json_valid(`logs_es`)),
  CONSTRAINT `roms_chk_13` CHECK (json_valid(`logs_pt`)),
  CONSTRAINT `roms_chk_14` CHECK (json_valid(`logs_tr`)),
  CONSTRAINT `roms_chk_15` CHECK (json_valid(`logs_id`)),
  CONSTRAINT `roms_chk_16` CHECK (json_valid(`logs_vi`)),
  CONSTRAINT `roms_chk_17` CHECK (json_valid(`logs_th`)),
  CONSTRAINT `roms_chk_18` CHECK (json_valid(`logs_ar`)),
  CONSTRAINT `roms_chk_19` CHECK (json_valid(`logs_in`)),
  CONSTRAINT `roms_chk_20` CHECK (json_valid(`logs_ug`)),
  CONSTRAINT `roms_chk_21` CHECK (json_valid(`logs_bo`))
) ENGINE=InnoDB AUTO_INCREMENT=53771 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;

-- 数据示例：52119,'taiko','taiko','HyperOS','HyperOS 3','cn','CnOO','F',1,'OS3.0.303.0.WOVCNXM','16.0','2026-04-22','2026-04-22','2026-04-27','taiko-ota_full-OS3.0.303.0.WOVCNXM-user-16.0-cafd2ead7a.zip','taiko_images_OS3.0.303.0.WOVCNXM_20260416.0000.00_16.0_cn_343def42ff.tgz','taiko_images_OS3.0.303.0.WOVCNXM_20260416.0000.00_16.0_cn_chinatelecom_251b6f1689.tgz',NULL,NULL,NULL,'2026-04-22',NULL,'{\"小米超级岛\": [\"新增 小米超级岛，信息触达更高效\", \"新增 支持下拉展开小窗，多任务场景高效处理\"]}','{\"Xiaomi HyperIsland\": [\"New: View all the important info at a glance with Xiaomi HyperIsland\"]}','2026-03-01'
