from dataclasses import dataclass, field
from typing import Dict


# ==================== 配置常量 ====================

@dataclass
class Constants:
	"""系统常量配置"""
	MIUI_KEY: bytes = field(default_factory=lambda: b"miuiotavalided11")
	MIUI_IV: bytes = field(default_factory=lambda: b"0102030405060708")
	CHECK_URL: str = "https://update.miui.com/updates/miotaV3.php"

	SDK_VERSIONS: Dict[str, str] = field(default_factory=lambda: {
		"17.0": "37","16.0": "36", "16": "36", "15": "35", "15.0": "35",
		"14": "34", "14.0": "34", "13.0": "33", "13": "33",
		"12": "31", "12.0": "31", "11": "30", "11.0": "30",
		"10": "29", "10.0": "29", "9": "28", "9.0": "28",
		"8.1": "27", "8": "26", "8.0": "26", "7.1": "25",
		"7": "24", "7.0": "24", "6": "23", "6.0": "23",
		"5.1": "22", "5": "21", "5.0": "21", "4.4": "19",
		"4.3": "18", "4.2": "17", "4.1": "16", "4": "14",
		"4.0": "14", "2.3.6": "10", "2.3.5": "10",
		"2.3": "9", "2": "9", "2.0": "9"
	})

	ANDROID_CODES: Dict[str, str] = field(default_factory=lambda: {
		"17.0": "X", "16.0": "W", "15.0": "V", "14.0": "U", "13.0": "T",
		"12.0": "S", "11.0": "R", "10.0": "Q", "9.0": "P",
		"8.1": "O", "8.0": "O", "7.1": "N", "7.0": "N",
		"6.0": "M", "5.1": "L", "5.0": "L", "4.4": "K",
		"4.3": "J", "4.2": "J", "4.1": "J", "4.0": "I"
	})


# 全局常量示例
_const = Constants()


branches = [
	{
		"id" : 1,
		"branch" : "F",
		"name_zh" : "中国大陆正式版",
		"name_en" : "China Mainland Stable",
		"btag" : "CnOO",
		"code" : "",
		"tag" : "CNXM",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 2,
		"branch" : "F",
		"name_zh" : "中国大陆Beta",
		"name_en" : "China Beta",
		"btag" : "CnOB",
		"code" : "",
		"tag" : "CNXM",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 3,
		"branch" : "F",
		"name_zh" : "体验增强版 Beta",
		"name_en" : "Enhanced Experience Beta",
		"btag" : "Beta",
		"code" : "",
		"tag" : "CNXM",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 4,
		"branch" : "X",
		"name_zh" : "中国大陆开发版",
		"name_en" : "China Dev",
		"btag" : "Dev",
		"code" : "",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 5,
		"branch" : "X",
		"name_zh" : "中国大陆体验版",
		"name_en" : "China Alpha",
		"btag" : "CNAL",
		"code" : "_alpha",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 6,
		"branch" : "F",
		"name_zh" : "中国大陆推荐版",
		"name_en" : "China Mainland Suggested Edition",
		"btag" : "CNST",
		"code" : "",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 7,
		"branch" : "F",
		"name_zh" : "中国电信推荐版",
		"name_en" : "China Telecom Suggested Edition",
		"btag" : "CNTT",
		"code" : "",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 8,
		"branch" : "F",
		"name_zh" : "中国联通推荐版",
		"name_en" : "China Unicom Suggested Edition",
		"btag" : "CNUT",
		"code" : "",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 9,
		"branch" : "F",
		"name_zh" : "标准青春版推荐版",
		"name_en" : "Suggested Edition for Mi 1 Lite",
		"btag" : "CNLT",
		"code" : "",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 10,
		"branch" : "F",
		"name_zh" : "原生安卓",
		"name_en" : "Stock Android",
		"btag" : "GOST",
		"code" : "",
		"tag" : "",
		"carrier" : [''],
		"region" : "cn",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 11,
		"branch" : "F",
		"name_zh" : "中国大陆演示机系统",
		"name_en" : "China Mainland MiStore Demo",
		"btag" : "CnOD",
		"code" : "_demo",
		"tag" : "CNDM",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 0,
		"ep" : 0
	},
	{
		"id" : 12,
		"branch" : "F",
		"name_zh" : "中国大陆政企标准版",
		"name_en" : "China Mainland Enterprise Standard",
		"btag" : "EPSTD",
		"code" : "_ep_stdee",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 1,
		"ep" : 1
	},
	{
		"id" : 13,
		"branch" : "F",
		"name_zh" : "中国大陆企业版(CE)",
		"name_en" : "China Mainland Enterprise(CE)",
		"btag" : "EPSCE",
		"code" : "_ep_stdce",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 0,
		"ep" : 1
	},
	{
		"id" : 14,
		"branch" : "F",
		"name_zh" : "中国大陆企业版(YUNKE)",
		"name_en" : "China Mainland Enterprise(YUNKE)",
		"btag" : "EPYKE",
		"code" : "_ep_yunke",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 0,
		"ep" : 1
	},
	{
		"id" : 15,
		"branch" : "F",
		"name_zh" : "中国大陆企业版(EPXY)",
		"name_en" : "China Mainland Enterprise(EPXY)",
		"btag" : "EPXYE",
		"code" : "_ep_xy",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 0,
		"ep" : 1
	},
	{
		"id" : 16,
		"branch" : "F",
		"name_zh" : "中国大陆企业版(EPYY)",
		"name_en" : "China Mainland Enterprise(EPYY)",
		"btag" : "EPYYE",
		"code" : "_ep_yy",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 0,
		"ep" : 1
	},
	{
		"id" : 17,
		"branch" : "F",
		"name_zh" : "中国大陆企业版(EPSDLYBJCG)",
		"name_en" : "China Mainland Enterprise(EPSDLYBJCG)",
		"btag" : "EPSDL",
		"code" : "_ep_sdlybjcg",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 0,
		"ep" : 1
	},
	{
		"id" : 18,
		"branch" : "F",
		"name_zh" : "中国大陆企业版(TBKJ)",
		"name_en" : "China Mainland Enterprise(TBKJ)",
		"btag" : "EPTBK",
		"code" : "_ep_tbkj",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 0,
		"ep" : 1
	},
	{
		"id" : 19,
		"branch" : "F",
		"name_zh" : "中国大陆企业版(TL)",
		"name_en" : "China Mainland Enterprise(TL)",
		"btag" : "EPTLE",
		"code" : "_tl",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 0,
		"ep" : 1
	},
	{
		"id" : 20,
		"branch" : "F",
		"name_zh" : "中国大陆企业版(ETLY)",
		"name_en" : "China Mainland Enterprise(ETLY)",
		"btag" : "EPTLY",
		"code" : "_ep_tly",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 0,
		"ep" : 1
	},
	{
		"id" : 21,
		"branch" : "F",
		"name_zh" : "中国大陆企业版(XDJA)",
		"name_en" : "China Mainland Enterprise(XDJA)",
		"btag" : "EPXDJ",
		"code" : "_ep_xdja",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 0,
		"ep" : 1
	},
	{
		"id" : 22,
		"branch" : "F",
		"name_zh" : "中国大陆企业版(EPYX)",
		"name_en" : "China Mainland Enterprise(EPYX)",
		"btag" : "EPYXE",
		"code" : "_ep_yx",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 0,
		"ep" : 1
	},
	{
		"id" : 23,
		"branch" : "F",
		"name_zh" : "中国大陆企业版(KYWL)",
		"name_en" : "China Mainland Enterprise(KYWL)",
		"btag" : "EPKYW",
		"code" : "_ep_kywl",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 0,
		"ep" : 1
	},
	{
		"id" : 24,
		"branch" : "F",
		"name_zh" : "中国大陆企业版(CQRCB)",
		"name_en" : "China Mainland Enterprise(CQRCB)",
		"btag" : "EPCQR",
		"code" : "_ep_cqrcb",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 0,
		"ep" : 1
	},
	{
		"id" : 25,
		"branch" : "F",
		"name_zh" : "中国大陆企业版(EPEC)",
		"name_en" : "China Mainland Enterprise(EPEC)",
		"btag" : "EPECE",
		"code" : "_ep_ec",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 0,
		"ep" : 1
	},
	{
		"id" : 26,
		"branch" : "F",
		"name_zh" : "中国大陆企业版(SXHT)",
		"name_en" : "China Mainland Enterprise(SXHT)",
		"btag" : "EPSXH",
		"code" : "_ep_sxht",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 0,
		"ep" : 1
	},
	{
		"id" : 27,
		"branch" : "F",
		"name_zh" : "中国大陆企业版(YFAN)",
		"name_en" : "China Mainland Enterprise(YFAN)",
		"btag" : "EPYFA",
		"code" : "_ep_yfan",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 0,
		"ep" : 1
	},
	{
		"id" : 28,
		"branch" : "F",
		"name_zh" : "中国大陆企业版(TKGWDL)",
		"name_en" : "China Mainland Enterprise(TKGWDL)",
		"btag" : "EPTKG",
		"code" : "_ep_tkgwdl",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 0,
		"ep" : 1
	},
	{
		"id" : 29,
		"branch" : "F",
		"name_zh" : "中国大陆企业版(CJCC)",
		"name_en" : "China Mainland Enterprise(CJCC)",
		"btag" : "EPCJC",
		"code" : "_ep_cjcc",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 0,
		"ep" : 1
	},
	{
		"id" : 30,
		"branch" : "X",
		"name_zh" : "安卓开发者预览版",
		"name_en" : "Android Developer Preview Global",
		"btag" : "ADPC",
		"code" : "_pre_dpp",
		"tag" : "",
		"carrier" : ['','chinatelecom','chinamobile','chinaunicom'],
		"region" : "cn",
		"zone" : 1,
		"visibility" : 0,
		"ep" : 0
	},
	{
		"id" : 31,
		"branch" : "F",
		"name_zh" : "中国香港地区正式版",
		"name_en" : "China Hong Kong Stable",
		"btag" : "CNHK",
		"code" : "_hk_global",
		"tag" : "",
		"carrier" : [''],
		"region" : "hk",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 32,
		"branch" : "F",
		"name_zh" : "中国台湾地区正式版",
		"name_en" : "China Taiwan Stable",
		"btag" : "CNTP",
		"code" : "_tw_global",
		"tag" : "TWXM",
		"carrier" : [''],
		"region" : "tw",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 33,
		"branch" : "X",
		"name_zh" : "国际开发版",
		"name_en" : "Global Dev",
		"btag" : "GDev",
		"code" : "_global",
		"tag" : "",
		"carrier" : [''],
		"region" : "global",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 34,
		"branch" : "F",
		"name_zh" : "国际正式版",
		"name_en" : "Global Stable",
		"btag" : "GBOO",
		"code" : "_global",
		"tag" : "MIXM",
		"carrier" : [''],
		"region" : "global",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 35,
		"branch" : "F",
		"name_zh" : "国际 DC 正式版",
		"name_en" : "Global DC Stable",
		"btag" : "GBDC",
		"code" : "_dc_global",
		"tag" : "MIDC",
		"carrier" : ['dc'],
		"region" : "global",
		"zone" : 2,
		"visibility" : 0,
		"ep" : 0
	},
	{
		"id" : 36,
		"branch" : "F",
		"name_zh" : "国际ThreeHK运营商定制版",
		"name_en" : "Global ThreeHK Carrier Edition",
		"btag" : "GBHG",
		"code" : "_h3g_global",
		"tag" : "MIHG",
		"carrier" : [''],
		"region" : "global",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 37,
		"branch" : "X",
		"name_zh" : "安卓开发者预览版国际版",
		"name_en" : "Android Developer Preview Global",
		"btag" : "ADPG",
		"code" : "_pre_dpp_global",
		"tag" : "",
		"carrier" : [''],
		"region" : "global",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 38,
		"branch" : "F",
		"name_zh" : "欧洲EEA正式版",
		"name_en" : "Europe EEA Stable",
		"btag" : "EEAO",
		"code" : "_eea_global",
		"tag" : "EUXM",
		"carrier" : [''],
		"region" : "eea",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 39,
		"branch" : "F",
		"name_zh" : "欧洲Orange运营商定制版",
		"name_en" : "Europe Orange Carrier Edition",
		"btag" : "EUOR",
		"code" : "_eea_or_global",
		"tag" : "EUOR",
		"carrier" : ['orange'],
		"region" : "eea",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 40,
		"branch" : "F",
		"name_zh" : "欧洲Vodafone运营商定制版",
		"name_en" : "Europe Vodafone Carrier Edition",
		"btag" : "EUVF",
		"code" : "_eea_vf_global",
		"tag" : "EUVF",
		"carrier" : ['vf'],
		"region" : "eea",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 41,
		"branch" : "F",
		"name_zh" : "欧洲ThreeHK运营商定制版",
		"name_en" : "Europe ThreeHK Carrier Edition",
		"btag" : "EUHG",
		"code" : "_eea_hg_global",
		"tag" : "EUHG",
		"carrier" : ['h3g'],
		"region" : "eea",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 42,
		"branch" : "F",
		"name_zh" : "欧洲Telefonica运营商定制版",
		"name_en" : "Europe Telefonica Carrier Edition",
		"btag" : "EUTF",
		"code" : "_eea_tf_global",
		"tag" : "EUTF",
		"carrier" : ['tf'],
		"region" : "eea",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 43,
		"branch" : "F",
		"name_zh" : "欧洲Altice(SFR)运营商定制版",
		"name_en" : "Europe Altice(SFR) Carrier Edition",
		"btag" : "EUSF",
		"code" : "_eea_sf_global",
		"tag" : "EUSF",
		"carrier" : ['sf'],
		"region" : "eea",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 44,
		"branch" : "F",
		"name_zh" : "欧洲TIM运营商定制版",
		"name_en" : "Europe TIM Carrier Edition",
		"btag" : "EUTI",
		"code" : "_eea_ti_global",
		"tag" : "EUTI",
		"carrier" : ['ti'],
		"region" : "eea",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 45,
		"branch" : "F",
		"name_zh" : "欧洲Bouygues Telecom运营商定制版",
		"name_en" : "Europe Bouygues Telecom Carrier Edition",
		"btag" : "EUBY",
		"code" : "_eea_by_global",
		"tag" : "EUBY",
		"carrier" : ['by'],
		"region" : "eea",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 46,
		"branch" : "F",
		"name_zh" : "俄罗斯正式版",
		"name_en" : "Russia Stable",
		"btag" : "RUSO",
		"code" : "_ru_global",
		"tag" : "RUXM",
		"carrier" : [''],
		"region" : "ru",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 47,
		"branch" : "F",
		"name_zh" : "印度正式版",
		"name_en" : "India Stable",
		"btag" : "INSO",
		"code" : "_in_global",
		"tag" : "INXM",
		"carrier" : [''],
		"region" : "in",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 48,
		"branch" : "F",
		"name_zh" : "印度正式版",
		"name_en" : "India Stable",
		"btag" : "INRF",
		"code" : "_in_rf_global",
		"tag" : "INRF",
		"carrier" : [''],
		"region" : "in",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 49,
		"branch" : "F",
		"name_zh" : "印度正式版",
		"name_en" : "India Stable",
		"btag" : "INSO",
		"code" : "_in_fk_global",
		"tag" : "INFK",
		"carrier" : [''],
		"region" : "in",
		"zone" : 2,
		"visibility" : 0,
		"ep" : 0
	},
	{
		"id" : 50,
		"branch" : "F",
		"name_zh" : "印度尼西亚正式版",
		"name_en" : "Indonesia Stable",
		"btag" : "IDSO",
		"code" : "_id_global",
		"tag" : "IDXM",
		"carrier" : [''],
		"region" : "id",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 51,
		"branch" : "F",
		"name_zh" : "马来西亚正式版",
		"name_en" : "Malaysia Stable",
		"btag" : "MYGS",
		"code" : "",
		"tag" : "",
		"carrier" : [''],
		"region" : "my",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 52,
		"branch" : "F",
		"name_zh" : "新加坡正式版",
		"name_en" : "Singapore Stable",
		"btag" : "SGGS",
		"code" : "_sg_global",
		"tag" : "",
		"carrier" : [''],
		"region" : "sg",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 53,
		"branch" : "X",
		"name_zh" : "新加坡开发版",
		"name_en" : "Singapore Beta",
		"btag" : "SGGD",
		"code" : "_sg_global",
		"tag" : "",
		"carrier" : [''],
		"region" : "sg",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 54,
		"branch" : "F",
		"name_zh" : "泰国AIS运营商定制版",
		"name_en" : "Thailand Stable AIS Carrier Edtion",
		"btag" : "THAS",
		"code" : "_th_as_global",
		"tag" : "THAS",
		"carrier" : ['as'],
		"region" : "th",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 55,
		"branch" : "F",
		"name_zh" : "土耳其正式版",
		"name_en" : "Turkey Stable",
		"btag" : "TRSO",
		"code" : "_tr_global",
		"tag" : "TRXM",
		"carrier" : [''],
		"region" : "tr",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 56,
		"branch" : "F",
		"name_zh" : "日本KDDI电信运营商定制版",
		"name_en" : "Japan Stable KDDI Carrier Edtion",
		"btag" : "JPKD",
		"code" : "_jp_kd_global",
		"tag" : "JPKD",
		"carrier" : [''],
		"region" : "jp",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 57,
		"branch" : "F",
		"name_zh" : "日本正式版",
		"name_en" : "Japan Stable",
		"btag" : "JAPS",
		"code" : "_jp_global",
		"tag" : "JPXM",
		"carrier" : [''],
		"region" : "jp",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 58,
		"branch" : "F",
		"name_zh" : "日本SoftBank运营商定制版",
		"name_en" : "Japan Stable SoftBank Carrier Edtion",
		"btag" : "JPSB",
		"code" : "_jp_sb_global",
		"tag" : "JPSB",
		"carrier" : ['sb'],
		"region" : "jp",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 59,
		"branch" : "F",
		"name_zh" : "韩国正式版",
		"name_en" : "South Korea Stable",
		"btag" : "SKSO",
		"code" : "_kr_global",
		"tag" : "KRXM",
		"carrier" : [''],
		"region" : "kr",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 60,
		"branch" : "F",
		"name_zh" : "韩国LG U+ 运营商定制版",
		"name_en" : "South Korea Stable LG U+ Carrier Edtion",
		"btag" : "SKLG",
		"code" : "_kr_gu_global",
		"tag" : "KRGU",
		"carrier" : [''],
		"region" : "kr",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 61,
		"branch" : "F",
		"name_zh" : "韩国KTF 运营商定制版",
		"name_en" : "South Korea Stable KTF Carrier Edtion",
		"btag" : "SKKT",
		"code" : "_kr_kt_global",
		"tag" : "KRKT",
		"carrier" : [''],
		"region" : "kr",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 62,
		"branch" : "F",
		"name_zh" : "韩国SK电讯运营商定制版",
		"name_en" : "South Korea Stable SK Telecom Carrier Edtion",
		"btag" : "SKSK",
		"code" : "_kr_sk_global",
		"tag" : "KRSK",
		"carrier" : [''],
		"region" : "kr",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 63,
		"branch" : "F",
		"name_zh" : "拉丁美洲Claro运营商定制版",
		"name_en" : "Latin America Claro Carrier Edition",
		"btag" : "LMCR",
		"code" : "_lm_cr_global",
		"tag" : "LMCR",
		"carrier" : ['cr'],
		"region" : "lm",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 64,
		"branch" : "F",
		"name_zh" : "墨西哥Telcel运营商定制版",
		"name_en" : "Mexico Stable Telcel Carrier Edtion",
		"btag" : "MXTC",
		"code" : "_mx_tc_global",
		"tag" : "MXTC",
		"carrier" : ['tc'],
		"region" : "mx",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 65,
		"branch" : "F",
		"name_zh" : "智利Entel运营商定制版",
		"name_en" : "Chile Stable Entel Carrier Edtion",
		"btag" : "CLEN",
		"code" : "_cl_en_global",
		"tag" : "CLEN",
		"carrier" : [''],
		"region" : "cl",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 66,
		"branch" : "F",
		"name_zh" : "墨西哥AT&T运营商定制版",
		"name_en" : "Mexico Stable AT&T Carrier Edtion",
		"btag" : "MXAT",
		"code" : "_mx_at_global",
		"tag" : "MXAT",
		"carrier" : [''],
		"region" : "mx",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 67,
		"branch" : "F",
		"name_zh" : "南非MTN运营商定制版",
		"name_en" : "South Africa MTN Carrier Edtion",
		"btag" : "ZAMT",
		"code" : "_za_mt_global",
		"tag" : "ZAMT",
		"carrier" : ['mt'],
		"region" : "za",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 68,
		"branch" : "F",
		"name_zh" : "南非Vodacom运营商定制版",
		"name_en" : "South Africa Vodacom Carrier Edtion",
		"btag" : "ZAVC",
		"code" : "_za_vc_global",
		"tag" : "ZAVC",
		"carrier" : ['vc'],
		"region" : "za",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 69,
		"branch" : "F",
		"name_zh" : "拉丁美洲Movistar运营商定制版",
		"name_en" : "Latin America Movistar Carrier Edition",
		"btag" : "LMMS",
		"code" : "_lm_ms_global",
		"tag" : "LMMS",
		"carrier" : ['movistar'],
		"region" : "lm",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 70,
		"branch" : "F",
		"name_zh" : "危地马拉Tigo运营商定制版",
		"name_en" : "Guatemala Tigo Carrier Edtion",
		"btag" : "GTTG",
		"code" : "_gt_tg_global",
		"tag" : "GTTG",
		"carrier" : ['gt'],
		"region" : "gt",
		"zone" : 2,
		"visibility" : 1,
		"ep" : 0
	},
	{
		"id" : 71,
		"branch" : "F",
		"name_zh" : "印度尼西亚 Demo",
		"name_en" : "Indonesia MiStore Demo",
		"btag" : "IDDM",
		"code" : "_id_global",
		"tag" : "IDDM",
		"carrier" : [''],
		"region" : "id",
		"zone" : 2,
		"visibility" : 0,
		"ep" : 0
	}
]

# OTA表单模板（保持原样）
HyperOSForm = {
		"obv": "OS1.0",
		"channel": "",
		"sys": "0",
		"bv": "816",
		"id": "",
		"sn": "0x0000043b716a25f1",
		"a": "0",
		"b": "F",
		"c": "14",
		"unlock": "0",
		"d": "marble",
		"lockZoneChannel": "normal",
		"f": "1",
		"ov": "OS1.0.2.0.UMRCNXM",
		"g": "9b65722a06722e8d8dffa35a9fd58586",
		"i": "14db85f96df2efc324323fa7679f0d847ff53f3bff7179ea0c778ce5d980bc03",
		"i2": "2cd7c24f21e33b236fc63f26d044227b96d8b39a80400654f88182322688793b",
		"isR": "0",
		"l": "zh_CN",
		"n": "",
		"p": "marble",
		"pb": "Redmi",
		"r": "CN",
		"v": "MIUI-V816.0.2.0.UMRCNXM",
		"sdk": "34",
		"pn": "marble",
		"options": {
				"zone": 1,
				"hashId": "dae7d50f696d7403",
				"ab": "1",
				"previewPlan": "0",
				"sv": 3,
				"av": "8.8.8",
				"cv": ""
		}
}
